CREATE TABLE Providers (
    Id SERIAL PRIMARY KEY,
    Name VARCHAR(255) NOT NULL
);

CREATE TABLE Articles (
    Id UUID PRIMARY KEY,
    Name VARCHAR(255) NOT NULL,
    Date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    Url VARCHAR(255) NOT NULL,
    Provider INT REFERENCES Providers(Id) NOT NULL
);
